### ISSUE TITLE
Drop Down Menus

### ISSUE THREAD

**Issue by wittedhaddock** [jrsinclair/jquery-dependent-questions#2]
How do I configure this auto-load for a drop-down menu?
&lt;form action="?" id="myform">
  &lt;fieldset class="form-question">
    &lt;legend>What type of event are you planning?</legend>
    &lt;div class="general-event-question">
      &lt;select name="eventType" id="eventTypeDropDown">
        &lt;option value="wedding" name="eventType" id="isAWeddingEvent">A Wedding</option>
        &lt;option value="general" name="eventType" id="isAGeneralEvent" for="eventTypeDropDown">
          <&lt;abel for="isAGeneralEvent">A General Event</label>
        &lt;/option>

```
  &lt;/select>
&lt;/div>
```

  &lt;/fieldset>
  &lt;fieldset data-depends-on="eventType=isAGeneralEvent">
    &lt;p>hi</p>
    &lt;div class="form-question">
      &lt;label for="extra">What else would you like to add?</label>
      &lt;input type="text" name="extra" id="extra"/>
    &lt;/div>
  &lt;/fieldset>
&lt;/form>
It seems like this only works for tags akin to &lt;input>

Thank you!

**Comment by jrsinclair** [comment]
Hi WittedHaddock,

Try switching your `data-depends-on` attribute to use the _value_ of the option, rather than the _ID_. For example:

``` html
<fieldset data-depends-on="eventType=general">
…
</fieldset>
```

I've created an example using the above code at JSFidle, so you can see it working: http://jsfiddle.net/JGaV3/
